### ISSUE TITLE
Functional tests: Review and fixes required

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests#2]
The current functional test suite does not work for our secure banking deployment.
Much of the content is not relevant for securebanking (Eg, creating a new user to test dynamic registration).

We need a test suite for securebanking that tests the relevant functionality, this will involve cutting out much of the current functional tests or perhaps even building up a new test suite from scratch.

We have a list of testable endpoints in another [issue](https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/71#issuecomment-844127688). 

### tasks
- [x] Review/Config IG for dynamic registration
- [x] Review/Config AM for dynamic registration
- [x] Review/Update [fidc-initializer](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-fidc-initializer) to persist the configuration
- [x] Review and apply fixes and changes on Functional test
