### ISSUE TITLE
Write and Run the tests for all versions/endpoints enabled in a cluster dynamically

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests#5]
As an Open Banking developer
I want write and run the functional tests depending of versions/endpoints enabled in a cluster and defined in the discovery
So that I can adequately test all api version implemented and enabled

## Acceptance criteria
- Pattern to run all versions dynamically and ignore these versions and endpoints disabled in a platform

## Tasks
- [ ] Examine existing solution in `securebanking-openbanking-uk-functional-tests`.
- [ ] Investigate possible options to write and run dynamically the tests for enabled versions
- [ ] Implement a solution to avoid write unit tests for each endpoint per version

### Release Notes

Affected App: securebanking-openbanking-uk-functional-tests
